# Generated by Django 6.1 on 2026-08-18 08:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_payment_channel', models.CharField(choices=[('MPESA_B2C', 'M-Pesa Direct'), ('MANUAL_BANK', 'Manual Bank Transfer')], default='MPESA_B2C', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
