# Generated by Django 6.1 on 2026-08-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='preferred_payment_channel',
        ),
        migrations.AddField(
            model_name='member',
            name='payout_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa B2C'), ('CASH', 'Cash at Counter'), ('BANK', 'Bank Transfer')], default='MPESA', max_length=10),
        ),
    ]
