# Generated by Django 6.1 on 2026-08-18 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_field_liters', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('plant_received_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SYNCED', 'Synced'), ('CLOSED_AUDITED', 'Closed & Audited')], default='OPEN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('liters_collected', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quality_status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='ACCEPTED', max_length=20)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='members.member')),
            ],
        ),
    ]
