# Generated by Django 6.1 on 2026-08-19 10:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrovet', '0001_initial'),
        ('members', '0002_remove_member_preferred_payment_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrovetRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA_DIRECT', 'M-Pesa Direct/Paybill'), ('BANK_DEPOSIT', 'Bank Deposit')], default='CASH', max_length=15)),
                ('reference_number', models.CharField(help_text='M-Pesa Code or Receipt No.', max_length=50, unique=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrovet_repayments', to='members.member')),
            ],
        ),
    ]
